"""create koty table

Revision ID: 141cf40a5119
Revises: 
Create Date: 2026-01-29 21:18:07.339288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141cf40a5119'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Koty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Imie', sa.String(length=100), nullable=True),
    sa.Column('Rasa', sa.String(length=100), nullable=True),
    sa.Column('Wiek', sa.Integer(), nullable=True),
    sa.Column('DoAdopcji', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Koty', schema='dbo')
    # ### end Alembic commands ###
